events {
    worker_connections 1024;
}

http {
    # Подключаем стандартные MIME-типы nginx
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 443 ssl;
        server_name upstream;

        ssl_certificate     /etc/nginx/certs/upstream.crt;
        ssl_certificate_key /etc/nginx/certs/upstream.key;

        root /usr/share/nginx/html;

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        location /error {
            return 500 "Internal Server Error";
        }

        location /file.txt {
            alias /usr/share/nginx/html/file.txt;
            default_type application/octet-stream;
        }
    }
}
